name: Go Kubernetes Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21' # Adjust if your project uses a different Go version

    - name: Set up KinD Cluster
      uses: helm/kind-action@v1.10.0
      # The action sets up a single-node KinD cluster named 'kind'.
      # It also exports the KUBECONFIG path as an output 'kubeconfig'.

    - name: Run Go Kubernetes tests
      run: |
        # The kind-action automatically sets the kubectl context.
        # Verify kubectl can connect (optional but good for debugging)
        echo "Verifying kubectl connection..."
        kubectl cluster-info
        kubectl get nodes

        echo "Running Go tests..."
        # The test code uses client-go which respects the KUBECONFIG env var.
        go test -v -timeout 5m ./... # Increased timeout for cluster operations
      env:
        # Pass the kubeconfig path generated by kind-action to the Go test environment
        KUBECONFIG: ${{ steps.Set_up_KinD_Cluster.outputs.kubeconfig }} # Make sure step ID matches

